### PR TITLE
New PCL from end of August

### PR DESCRIPTION
**Pull request by schymane**
...added to Docker file

### CODE REVIEW

**Comment by sneumann** [comment]
Updated docker image on https://hub.docker.com/r/ipbhalle/metfragweb/tags
Deployed on https://msbi.ipb-halle.de/MetFragBeta/ now.
Thanks, Steffen

**Comment by schymane** [comment]
Thanks @sneumann ! The new data file is there, but the new sorting from @meier-rene doesn't really seem to work. I'm not quite sure how to fix, any ideas?
The top one is definitely not the newest ... and the newest one comes middle in other files older than it ... (see image).
I could definitely see changes to the docker file in the one I committed. 

image

**Comment by meier-rene** [comment]
I hope I can clarify things here: The sorting is working as designed, but not as you expected. Its not looking at the names, because there is no consistent creation date naming scheme. Its just considering the creation date of the file on the hard disc. Please have a look at the Dockerfile. The later the file is downloaded, the newer it is, the closer it appears to the top. The final order in the dropdown menu is exactly the opposite of the order of the library files in the Dockerfile. If you want to change the order, you do not need to change the name, but put the download more to the end of the Dockerfile.

**Comment by schymane** [comment]
Thanks for clarifying @meier-rene - CynaoMetDB and COCONUT out of date order confused me ... now I understand how you've constructed the Dockerfile (I think). I just committed https://github.com/ipb-halle/MetFragRelaunched/pull/103 - which will hopefully adjust the order to be as I hope (at least according to what I now think I understand)

**Comment by schymane** [comment]
Updated version on MetFragBeta is looking great!

**Pull request merged**
