### PR TITLE
Updated PubChemLite (July 2022) and attempted reorder

### PR DESCRIPTION
**Pull request by schymane**
Updated to latest version of PubChemLite and attempted to reorder the local databases to get more recent files closer to the top. Let's see if it works ... (!)

### CODE REVIEW

**Comment by meier-rene** [comment]
Hi Emma,
thanks for the effort. In the moment we preparing a new release/rollout of MetFrag with updated reference libraries included. That's why I would like to address this ordering issue. I had a look into the code and atm it is not guaranteeing any particular order, but I can include a sorting step in the code, e.g. I can sort by last modification time.
By default wget is reproducing the modification time of the source. I tried this and it looks like the modification time of the files at zenodo is not related to the publication time of the dataset. :cry:

My sugestion: we can use the touch command in the Dockerfile to set the modification time after downloading and they will be displayed in the reverse order of 'touching', because newest files will be displayed on top. I guess the order of downloads is exactly the order you want to have in the dropdown menu? I will modify the Dockerfile to reproduce this order via the modification times of the files(means downloading in opposite order because last downloaded means newest modification time after touch).

**Comment by schymane** [comment]
Thanks Rene! Yes this is what I was attempting, this will be fine if we assume the most recent CSVs are the ones users are most interested in (i.e. "newest developments are the coolest"), but won't catch cases where we may have some CSVs that are older but of greater interest than other interim developments. Is there a way we can override the default order manually somehow (_e.g._ prioritize certain databases to the top)? There are a lot of files now, and perhaps it would be useful to sort those of most interest to most users towards the top?
Perhaps we can see what your suggestion does first, if this solves the issue elegantly for now, then maybe we don't need fancier controls?

**Comment by meier-rene** [comment]
I think it should be as easy as listing them in the Dockerfile exactly in the opposite order you want them to appear in the Dropdown menu. After each download command we need to apply a touch on the downloaded file to modify the timestamp of the file. I will check in this modifications shortly after testing and than you can tweak the order.

**Comment by schymane** [comment]
OK great, I thought something like this should work implicitly (this is what I was trying to achieve). The only caveat I see here is that some files may take longer to download (some files are a LOT bigger than others), but if they download sequentially, this should eliminate this factor. Happy to tweak a couple of times until it's working reasonably well ;-)

**Pull request merged**
